@echo off
echo Installing requirements...
pip install -r requirements.txt
echo Making migrations...
python manage.py makemigrations
python manage.py migrate
echo Starting server...
python manage.py runserver
pause
