from django.urls import path
from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("members/", views.member_list, name="member_list"),
    path("members/add/", views.member_create, name="member_create"),
    path("members/import/", views.import_members, name="import_members"),
    path("members/<int:pk>/edit/", views.member_update, name="member_update"),
    path("members/<int:pk>/portal-access/", views.member_portal_access, name="member_portal_access"),
    path("members/<int:pk>/notes/add/", views.add_member_note, name="add_member_note"),
    path("members/<int:pk>/send-reminder/", views.send_member_reminder_view, name="send_member_reminder"),
    path("members/<int:pk>/statement/", views.member_statement, name="member_statement"),
    path("members/<int:pk>/", views.member_detail, name="member_detail"),
    path("payments/", views.payment_list, name="payment_list"),
    path("payments/add/", views.payment_create, name="payment_create"),
    path("payments/<int:pk>/edit/", views.payment_update, name="payment_update"),
    path("payments/<int:pk>/delete/", views.payment_delete, name="payment_delete"),
    path("payments/<int:pk>/refund/", views.payment_refund, name="payment_refund"),
    path("payments/<int:pk>/receipt/", views.payment_receipt, name="payment_receipt"),
    path("payments/approvals/", views.payment_approvals, name="payment_approvals"),
    path("payments/approvals/<int:pk>/<str:decision>/", views.review_payment_approval, name="review_payment_approval"),
    path("activity-funds/request/", views.request_activity_fund, name="request_activity_fund"),
    path("activity-funds/", views.activity_fund_requests, name="activity_fund_requests"),
    path("activity-funds/<int:pk>/<str:decision>/", views.review_activity_fund_request, name="review_activity_fund_request"),
    path("roles/", views.role_management, name="role_management"),
    path("notifications/", views.notification_list, name="notification_list"),
    path("audit-trail/", views.audit_trail, name="audit_trail"),
    path("reminders/settings/", views.reminder_settings, name="reminder_settings"),
    path("reminders/bulk/", views.bulk_reminders, name="bulk_reminders"),
    path("due-calendar/", views.due_calendar, name="due_calendar"),
    path("exports/members.csv", views.export_members_csv, name="export_members_csv"),
    path("exports/payments.csv", views.export_payments_csv, name="export_payments_csv"),
    path("portal/", views.member_portal, name="member_portal"),
    path("member-portal/", views.public_member_portal, name="public_member_portal"),
    path("member-portal/logout/", views.public_member_portal_logout, name="public_member_portal_logout"),
    path("api/members/", views.api_members, name="api_members"),
    path("api/payments/", views.api_payments, name="api_payments"),
    path("debtors/", views.debtors, name="debtors"),
    path("reports/", views.reports, name="reports"),
    path("reports/smart-water-metering/", views.smart_water_report, name="smart_water_report"),
    path("reports/smart-water-metering/download/", views.download_smart_water_report, name="download_smart_water_report"),
]
